# Generated by Django 2.1.2 on 2018-11-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='string', max_length=150)),
                ('category', models.CharField(default='string', max_length=150)),
                ('image', models.FileField(default='', upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('userlogid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='userlogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finalapp.UserLog'),
        ),
    ]
