# Generated by Django 2.1.2 on 2018-11-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_auto_20181103_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='userlogid',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
