# Generated by Django 2.1.2 on 2018-11-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_auto_20181103_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
