# Generated by Django 2.1.2 on 2018-12-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0012_document_countlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='username',
        ),
    ]
