# Generated by Django 2.1.2 on 2018-12-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0013_auto_20181208_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='username',
            new_name='user',
        ),
    ]
