# Generated by Django 2.1.2 on 2018-12-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_auto_20181208_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
